# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc-version = "0.8.18"
src = 'contracts'
out = 'out'
test = 'test2'
libs = ['lib']
optimizer = true
optimizer_runs = 200

# Do not change the block_gas_limit value, TaikoL2.t.sol depends on it.
block_gas_limit = 30000000 #30M

fs_permissions = [
  { access = "read", path = "./out"},
  { access = "read", path = "./deployments"},
  { access = "read", path = "./test2"}
]
