service: defender-as-code-test-project
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: mystack
  ssot: false

custom:
  config: ${file(secrets.${self:provider.stage}.yml)}

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

resources:
  actions:
    erc-20-vault-balance-drop:
      name: "ERC20Vault: Balance Drop"
      trigger:
        type: schedule
        frequency: 15
      paused: false
      path: ./actions/ERC20Vault-BalanceDrop.js

    sgx-verifier-verify-proof-failure-alert:
      name: "SGXVerifier: VerifyProof failure Alert"
      trigger:
        type: schedule
        frequency: 5
      paused: false
      path: ./actions/SGXVerifier-verifyProofFailure.js

    vaults-bridged-token-deployed:
      name: "Vaults: BridgedTokenDeployed"
      trigger:
        type: schedule
        frequency: 1440
      paused: false
      path: ./actions/Vaults-BridgedTokenDeployed.js

    er-20-vault-bridged-token-changed:
      name: "ER20Vault : BridgedTokenChanged"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/ER20Vault-BridgedTokenChanged.js

    bridge-message-processed:
      name: "Bridge: MessageProcessed"
      trigger:
        type: schedule
        frequency: 15
      paused: false
      path: ./actions/Bridge-MessageProcessed.js

    taiko-l-1-calldata-tx-list-count:
      name: "TaikoL1: CalldataTxList Count"
      trigger:
        type: schedule
        frequency: 1440
      paused: false
      path: ./actions/TaikoL1-CalldataTxListCount.js

    guardian-prover-proving-auto-pause-enabled-alert:
      name: "GuardianProver: ProvingAutoPauseEnabled Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/GuardianProver-ProvingAutoPauseEnabled.js

    guardian-prover-conflicting-proofs-alert:
      name: "GuardianProver: ConflictingProofs Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/GuardianProver-ConflictingProofs.js

    guardian-prover-approved-count:
      name: "GuardianProver: Approved Count"
      trigger:
        type: schedule
        frequency: 15
      paused: false
      path: ./actions/GuardianProver-ApprovedCount.js

    guardian-prover-guardians-updated-alert:
      name: "GuardianProver: GuardiansUpdated Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/GuardianProver-GuardiansUpdated.js

    taiko-l-1-proving-paused-alert:
      name: "TaikoL1: ProvingPaused Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/TaikoL1-ProvingPaused.js

    taiko-l-1-transition-contested-count:
      name: "TaikoL1: TransitionContested Count"
      trigger:
        type: schedule
        frequency: 60
      paused: false
      path: ./actions/TaikoL1-TransitionContestedCount.js

    taiko-l-1-transition-proved-alert:
      name: "TaikoL1: TransitionProved Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/TaikoL1-TransitionProved.js

    taiko-l-1-block-verified-alert:
      name: "TaikoL1: BlockVerified Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/TaikoL1-BlockVerified.js

    taiko-l-1-block-proposed-alert:
      name: "TaikoL1: BlockProposed Alert"
      trigger:
        type: schedule
        frequency: 4
      paused: false
      path: ./actions/TaikoL1-BlockProposed.js

  policies:
    policy-Qe:
      eip1559-pricing: true
      private-transactions: false
    policy-hk:
      eip1559-pricing: true
      private-transactions: false
  contracts:
    pem-cert-chain-lib:
      name: pem_cert_chain_lib
      address: "0x02772b7B3a5Bea0141C993Dbb8D0733C19F46169"
      network: mainnet
    taiko-l-1:
      name: taikoL1
      address: "0x06a9Ab27c7e2255df1815E6CC0168d7755Feb19a"
      network: mainnet
    erc-721-vault:
      name: erc721_vault
      address: "0x1670000000000000000000000000000000000003"
      network: taikol2
    taiko-token:
      name: taiko_token
      address: "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
      network: mainnet
    p-256-verifier:
      name: p256_verifier
      address: "0x11A9ebA17EbF92b40fcf9a640Ebbc47Db6fBeab0"
      network: mainnet
    tier-provider:
      name: tierProvider
      address: "0x33879cDF01121dc7bCe011b461e64d791aE931F2"
      network: mainnet
    bridged-erc-1155:
      name: bridged_erc1155
      address: "0x39E4C1214e733639d059979079A151911e42791d"
      network: mainnet
    sig-verify-lib:
      name: sig_verify_lib
      address: "0x47bB416ee947fE4a4b655011aF7d6E3A1B80E6e9"
      network: mainnet
    assignment-hook:
      name: assignmentHook
      address: "0x537a2f0D3a5879b41BCb5A2afE2EA5c4961796F6"
      network: mainnet
    guardian-prover-minority:
      name: guardian_prover_minority
      address: "0x579A8d63a2Db646284CBFE31FE5082c9989E985c"
      network: mainnet
    rollup-address-manager:
      name: rollup_address_manager
      address: "0x1670000000000000000000000000000000010002"
      network: taikol2
    automata-dcap-attestation:
      name: automata_dcap_attestation
      address: "0x8d7C954960a36a7596d7eA4945dDf891967ca8A3"
      network: mainnet
    erc-20-vault:
      name: erc20_vault
      address: "0x1670000000000000000000000000000000000002"
      network: taikol2
    signal-service:
      name: signal_service
      address: "0x1670000000000000000000000000000000000005"
      network: taikol2
    guardian-prover:
      name: guardian_prover
      address: "0xE3D777143Ea25A6E031d1e921F396750885f43aC"
      network: mainnet
    shared-address-manager:
      name: shared_address_manager
      address: "0x1670000000000000000000000000000000000006"
      network: taikol2
    erc-1155-vault:
      name: erc1155_vault
      address: "0x1670000000000000000000000000000000000004"
      network: taikol2
    tier-sgx:
      name: tier_sgx
      address: "0xb0f3186FC1963f774f52ff455DC86aEdD0b31F81"
      network: mainnet
    bridged-erc-721:
      name: bridged_erc721
      address: "0xc4096E9ff1526Bd1840B65e9f45695135aC12De7"
      network: mainnet
    bridged-erc-20:
      name: bridged_erc20
      address: "0xcc5d488073FA918cBbd73B9A523F3858C4de7372"
      network: mainnet
    bridge:
      name: bridge
      address: "0x1670000000000000000000000000000000000001"
      network: taikol2
    taiko-l-2:
      name: taikoL2
      address: "0x1670000000000000000000000000000000010001"
      network: taikol2
  relayers:
    taiko-l-2-relayer:
      name: TaikoL2Relayer
      network: taikol2
      min-balance: "100000000000000000"
      policy: ${self:resources.policies.policy-Qe}
      api-keys:
        - key-1
    taiko-l-1-relayer:
      name: TaikoL1Relayer
      network: mainnet
      min-balance: "100000000000000000"
      policy: ${self:resources.policies.policy-hk}
      api-keys:
        - key-1
  notifications:
    discord-bridging:
      type: discord
      name: discord_bridging
      config:
        url: >-
          https://discord.com/api/webhooks/1235610195586187285/pT1ZoqTmEKcjtAt0JY6KxOeHP-_YP7mC3SG1janVZyuf99RE7XwymIFQ9iNlFiyxm41w
      paused: false
    discord-blocks:
      type: discord
      name: discord_blocks
      config:
        url: >-
          https://discord.com/api/webhooks/1235610046080221214/tEHgmjlZzZsuxGyv3bEPc1I_SGZ69ZmZ7JsF8ey5VEQadylYePXLjRyGCup1I96rTbRk
      paused: false
    discord-configs:
      type: discord
      name: discord_configs
      config:
        url: >-
          https://discord.com/api/webhooks/1235609859660185744/d6ygohFcXEJEj6zHlxGhLFqXq4lDfieLrFweae3SnsustZLF0q4aTKKHeuzmrgZBIcvy
      paused: false
  monitors:
    address-manager-l-2-address-set:
      name: "Address Manager (L2): AddressSet"
      type: BLOCK
      network: taikol2
      addresses:
        - "0x1670000000000000000000000000000000000006"
        - "0x1670000000000000000000000000000000010002"
      skip-abi-validation: false
      paused: false
      confirm-level: 1
      notify-config:
        timeout: 60000
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          **Match Reasons**

          {{ matchReasonsFormatted }}

          **Metadata**

          {{ metadataFormatted }}
        message-subject: "Defender Monitor: Address Manager (L2): AddressSet triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: MEDIUM
      conditions:
        event:
          - expression: null
            signature: AddressSet(uint64,bytes32,address,address)
    address-manager-l-1-address-set:
      name: "Address Manager (L1): AddressSet"
      type: BLOCK
      network: mainnet
      addresses:
        - "0x579f40D0BE111b823962043702cabe6Aaa290780"
        - "0xEf9EaA1dd30a9AA1df01c36411b5F082aA65fBaa"
      skip-abi-validation: false
      paused: false
      confirm-level: 9007199254740991
      notify-config:
        timeout: 60000
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          **Match Reasons**

          {{ matchReasonsFormatted }}

          **Metadata**

          {{ metadataFormatted }}
        message-subject: "Defender Monitor: Address Manager (L1): AddressSet triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: MEDIUM
      conditions:
        event:
          - expression: null
            signature: AddressSet(uint64,bytes32,address,address)
    taiko-l-2-pause-unpause:
      name: "TaikoL2: Pause/Unpause"
      type: BLOCK
      network: taikol2
      addresses:
        - "0xbd0999f42742ed29d3311fc5fb5c609be008e9e5"
        - "0x1670000000000000000000000000000000000001"
        - "0x1670000000000000000000000000000000000002"
        - "0x1670000000000000000000000000000000000003"
        - "0x1670000000000000000000000000000000000004"
        - "0x1670000000000000000000000000000000000005"
        - "0x1670000000000000000000000000000000000006"
        - "0x1670000000000000000000000000000000010001"
        - "0x1670000000000000000000000000000000010002"
      skip-abi-validation: true
      paused: false
      confirm-level: 1
      notify-config:
        timeout: 60000
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          **Match Reasons**

          {{ matchReasonsFormatted }}

          **Metadata**

          {{ metadataFormatted }}
        message-subject: "Defender Monitor: TaikoL2: Pause/Unpause triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: MEDIUM
      conditions:
        event:
          - expression: null
            signature: Paused(address)
          - expression: null
            signature: Unpaused(address)
    taiko-l-1-pause-unpause:
      name: "TaikoL1: Pause/Unpause"
      type: BLOCK
      network: mainnet
      addresses:
        - "0x02772b7B3a5Bea0141C993Dbb8D0733C19F46169"
        - "0x06a9Ab27c7e2255df1815E6CC0168d7755Feb19a"
        - "0x0b470dd3A0e1C41228856Fb319649E7c08f419Aa"
        - "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
        - "0x11A9ebA17EbF92b40fcf9a640Ebbc47Db6fBeab0"
        - "0x33879cDF01121dc7bCe011b461e64d791aE931F2"
        - "0x39E4C1214e733639d059979079A151911e42791d"
        - "0x47bB416ee947fE4a4b655011aF7d6E3A1B80E6e9"
        - "0x537a2f0D3a5879b41BCb5A2afE2EA5c4961796F6"
        - "0x579A8d63a2Db646284CBFE31FE5082c9989E985c"
        - "0x579f40D0BE111b823962043702cabe6Aaa290780"
        - "0x67281b15aee4d6b805bc755e439abd524dd8da8d"
        - "0x8d7C954960a36a7596d7eA4945dDf891967ca8A3"
        - "0x996282cA11E5DEb6B5D122CC3B9A1FcAAD4415Ab"
        - "0x9e0a24964e5397B566c1ed39258e21aB5E35C77C"
        - "0xE3D777143Ea25A6E031d1e921F396750885f43aC"
        - "0xEf9EaA1dd30a9AA1df01c36411b5F082aA65fBaa"
        - "0xa25e645ff9897b0282e5f17d36de5bca4ec21d6e"
        - "0xaf145913EA4a56BE22E120ED9C24589659881702"
        - "0xb0f3186FC1963f774f52ff455DC86aEdD0b31F81"
        - "0xc4096E9ff1526Bd1840B65e9f45695135aC12De7"
        - "0xcc5d488073FA918cBbd73B9A523F3858C4de7372"
        - "0xd60247c6848B7Ca29eDdF63AA924E53dB6Ddd8EC"
      skip-abi-validation: true
      paused: false
      confirm-level: 6
      notify-config:
        timeout: 60000
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          **Match Reasons**

          {{ matchReasonsFormatted }}

          **Metadata**

          {{ metadataFormatted }}
        message-subject: "Defender Monitor: TaikoL1: Pause/Unpause triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: MEDIUM
      conditions:
        event:
          - expression: null
            signature: Paused(address)
          - expression: null
            signature: Unpaused(address)
    taiko-mainnet-sgx-prover:
      name: Taiko Mainnet SGX Prover
      type: BLOCK
      network: mainnet
      addresses:
        - "0xb0f3186FC1963f774f52ff455DC86aEdD0b31F81"
      skip-abi-validation: false
      paused: false
      confirm-level: 1
      notify-config:
        timeout: 0
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          {{ matchReasonsFormatted }}
        message-subject: "Defender Monitor: Taiko Mainnet SGX Prover triggered"
        channels:
          - ${self:resources.notifications.discord-blocks}
        severity-level: LOW
      conditions:
        event:
          - expression: null
            signature: InstanceAdded(uint256,address,address,uint256)
          - expression: null
            signature: InstanceDeleted(uint256,address)
        function:
          - expression: null
            signature: >-
              verifyProof((bytes32,bytes32,address,uint64,bool,bool,address),(bytes32,bytes32,bytes32,bytes32),(uint16,bytes))
        transaction: status == "failed"
    taiko-mainnet-address-managers:
      name: Taiko Mainnet Address Managers
      type: BLOCK
      network: mainnet
      addresses:
        - "0xEf9EaA1dd30a9AA1df01c36411b5F082aA65fBaa"
        - "0x579f40D0BE111b823962043702cabe6Aaa290780"
      skip-abi-validation: false
      paused: false
      confirm-level: 1
      notify-config:
        timeout: 0
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          {{ matchReasonsFormatted }}
        message-subject: "Defender Monitor: Taiko Mainnet Address Managers triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: HIGH
      conditions:
        event:
          - expression: null
            signature: AddressSet(uint64,bytes32,address,address)
    taiko-mainnet-essential-contracts:
      name: Taiko Mainnet Essential Contracts
      type: BLOCK
      network: mainnet
      addresses:
        - "0xEf9EaA1dd30a9AA1df01c36411b5F082aA65fBaa"
        - "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
        - "0x9e0a24964e5397B566c1ed39258e21aB5E35C77C"
        - "0xd60247c6848B7Ca29eDdF63AA924E53dB6Ddd8EC"
        - "0x996282cA11E5DEb6B5D122CC3B9A1FcAAD4415Ab"
        - "0x0b470dd3A0e1C41228856Fb319649E7c08f419Aa"
        - "0x0b470dd3A0e1C41228856Fb319649E7c08f419Aa"
        - "0xaf145913EA4a56BE22E120ED9C24589659881702"
        - "0x579f40D0BE111b823962043702cabe6Aaa290780"
        - "0x06a9Ab27c7e2255df1815E6CC0168d7755Feb19a"
        - "0x537a2f0D3a5879b41BCb5A2afE2EA5c4961796F6"
        - "0x33879cDF01121dc7bCe011b461e64d791aE931F2"
        - "0xb0f3186FC1963f774f52ff455DC86aEdD0b31F81"
        - "0x579A8d63a2Db646284CBFE31FE5082c9989E985c"
        - "0xE3D777143Ea25A6E031d1e921F396750885f43aC"
        - "0x8d7C954960a36a7596d7eA4945dDf891967ca8A3"
      skip-abi-validation: false
      paused: false
      confirm-level: 1
      notify-config:
        timeout: 0
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          {{ matchReasonsFormatted }}
        message-subject: "Defender Monitor: Taiko Mainnet Essential Contracts triggered"
        channels:
          - ${self:resources.notifications.discord-configs}
        severity-level: HIGH
      conditions:
        event:
          - expression: null
            signature: AdminChanged(address,address)
          - expression: null
            signature: BeaconUpgraded(address)
          - expression: null
            signature: Initialized(uint8)
          - expression: null
            signature: OwnershipTransferStarted(address,address)
          - expression: null
            signature: OwnershipTransferred(address,address)
          - expression: null
            signature: Paused(address)
          - expression: null
            signature: Unpaused(address)
          - expression: null
            signature: Upgraded(address)
  forked-networks: {}
  private-networks:
    taikol-2:
      name: taikol2
      rpc-url: https://rpc.mainnet.taiko.xyz
      configuration:
        symbol: ETH
        eips:
          isEIP1559: true
  block-explorer-api-keys: {}
plugins:
  - "@openzeppelin/defender-as-code"
