env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FORK_DIFF }}

on:
  push:
    branches-ignore:
      - main
      - release-please-*
    paths:
      - "packages/fork-diff/**"

jobs:
  Deploy-Preview:
    runs-on: [taiko-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Read tag version from JSON
        run: |
          echo "TAG_VERSION=$(jq -r '.tagVersion' workspace/version_config.json)" >> $GITHUB_ENV

      - name: Checkout forkdiff
        uses: actions/checkout@v4
        with:
          repository: protolambda/forkdiff

      - name: Checkout taiko-geth
        uses: actions/checkout@v4
        with:
          repository: taikoxyz/taiko-geth

      - name: Checkout go-ethereum
        uses: actions/checkout@v4
        with:
          repository: ethereum/go-ethereum
          ref: ${{ env.TAG_VERSION }}

      - name: Ls
        run: ls

      - name: Replace tag version in configuration file
        run: |
          sed -i "s/{{TAG_VERSION}}/${{ env.TAG_VERSION }}/g" packages/fork-diff/fork.yml

      - name: Cat forkdiff/fork.yaml
        run: cat packages/fork-diff/fork.yaml

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.0

      - name: Generate index.html with forkdiff
        run: |
          cat packages/fork-diff/fork.yaml
          cp packages/fork-diff/fork.yaml forkdiff/fork.yaml
          cd forkdiff
          go run main.go -repo ../taiko-geth/ -upstream-repo ../go-ethereum/

      - name: Move generated index.html to vercel project root
        run: |
          mv forkdiff/index.html packages/fork-diff/index.html

      - name: Deploy Project Artifacts to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }}
