name: Monitors

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/monitors/**"

jobs:
  deploy-protocol-monitors:
    if: github.event.pull_request.draft == false
    runs-on: [taiko-runner]
    permissions:
      # Give the necessary permissions for stefanzweifel/git-auto-commit-action.
      contents: write
    steps:
      - name: Deploy Monitors on OZ Defender
        working-directory: packages/monitors/defender/mainnet
        env:
          SERVERLESS_API_KEY: ${{ secrets.DEFENDER_API_KEY }}
          SERVERLESS_API_SECRET: ${{ secrets.DEFENDER_API_SECRET }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          npx serverless login --token $SERVERLESS_ACCESS_KEY
          npx serverless deploy
