name: Auto Approve PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches-ignore:
      - release-please--branches--**

jobs:
  auto-approve:
    if: github.event.pull_request.draft == false && github.actor == 'dependabot[bot]'
    runs-on: [arc-runner-set]
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
