name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [taiko-runner]
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          changelog-types: >
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "chore", "section": "Chores", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false },
              { "type": "ci", "section": "Workflow", "hidden": false },
              { "type": "revert", "section": "Reverted Commits", "hidden": false },
              { "type": "build", "section": "Build", "hidden": false }
            ]
