name: Slither Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Workaround to prevent slither-action from trying to install JS deps.
      # Without this step, it detects the `package.json``, and since there is no
      # lockfile it defaults `npm install` which fails due to the preinstall
      # script to enforce pnpm. https://github.com/crytic/slither-action/issues/44#issuecomment-1338183656
      # Kudos to @optimism for the fix! :)
      - name: Remove package.json
        run: rm packages/protocol/package.json

      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        with:
          target: packages/protocol
          sarif: results.sarif
          fail-on: config
          slither-config: packages/protocol/slither.config.json
          slither-args: --triage-database packages/protocol/slither.db.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
