name: Solidity

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/protocol/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'packages/protocol/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'

    - name: protocol - Unit Tests
      working-directory: ./packages/protocol
      run: yarn && yarn clean && yarn test && yarn export:abi

    - name: protocol - Generate L2 Genesis
      working-directory: ./packages/protocol
      run: yarn test:genesis

    - name: protocol - Export ABIs
      working-directory: ./packages/protocol
      run: yarn export:abi

    - name: protocol - Deploy L1 Contracts
      working-directory: ./packages/protocol
      run: LOG_LEVEL=debug npx hardhat deploy_L1 --network hardhat --dao-vault 0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39 --team-vault 0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39 --l2-genesis-block-hash 0xee1950562d42f0da28bd4550d88886bc90894c77c9c9eaefef775d4c8223f259 --confirmations 1