name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "0 1 * * *" # Runs at 01:00 UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: "This issue is stale because it has been open for 45 days with no activity."
          stale-pr-message: "This PR is stale because it has been open for 45 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale."
          days-before-stale: 45
          days-before-close: 14
          exempt-issue-labels: "option.pinned,category.security"
          exempt-pr-labels: "option.pinned,category.security"
          stale-issue-label: "status.stale"
          stale-pr-label: "status.stale"
