name: "Push docker image to GAR"

on:
  push:
    branches: [main]
    tags:
      - "taiko-client-v*"
    paths:
      - "packages/taiko-client/**"

jobs:
  push-docker-image:
    name: Build and push docker image
    strategy:
      matrix:
        include:
          - runner: arc-runner-set
            platform: linux/amd64
          - runner: arc-runner-set-arm64
            platform: linux/arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Prepare Environment
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-docker.pkg.dev/evmchain/images/taiko-client
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/taiko-client/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
