name: Taikoon UI CI/CD
on:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/taikoon-ui--ci.yml

  # Deployment name follow the pattern: deploy_<appname(taikoon-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_taikoon-ui_mainnet_preview:
    needs: build-and-test
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "preview"
      flags: ""
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOON_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy_taikoon-ui_mainnet_production:
    needs: build-and-test
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "production"
      flags: "--prod"
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOON_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
