name: "CI"

on:
  push:
    branches: [main]
    paths:
      - "packages/taiko-client/**"
  pull_request:
    paths:
      - "packages/taiko-client/**"
      - "go.mod"
      - "go.sum"

jobs:
  dummy:
    runs-on: [taiko-runner]
    steps:
      - run: exit 1
