name: "Taiko Client Hive Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/taiko-client/**"
      - "go.mod"
      - "go.sum"

jobs:
  hive_tests:
    if: contains(github.event.pull_request.labels.*.name, 'option.workflow_on') && github.event.pull_request.draft == false && github.head_ref != 'release-please-*'
    name: hive tests
    runs-on: [arc-runner-set]
    timeout-minutes: 40

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Clone taikoxyz/hive
        run: git clone https://github.com/taikoxyz/hive.git /tmp/hive

      - name: Hive tests
        working-directory: packages/taiko-client
        run: |
          export HIVE_DIR=/tmp/hive
          go test -v -p=1 ./integration_test -timeout=2400s
