name: "Taiko Client Github Pages"

on:
  push:
    branches: [main]
    paths:
      - "packages/taiko-client/**"

jobs:
  swagger-gen:
    runs-on: [arc-runner-set]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install swaggo
        run: |
          export CGO_ENABLED=0
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger documentation
        run: |
          export CGO_ENABLED=0
          cd packages/taiko-client
          ./scripts/gen_swagger_json.sh

      - name: Commit Swagger docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -u
            git commit -m "Update Swagger documentation"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: [arc-runner-set]
    needs: swagger-gen
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/taiko-client/docs # Set this to where your `index.html` is located
          publish_branch: gh-pages
          destination_dir: soft-block-apis
