name: Update documentation

on:
  pull_request:
    types: [closed]
    paths:
      - "packages/protocol/**"
jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run the command to update the documentation
        run: pnpm -F protocol export:docs

      - name: Stage all modified and untracked files
        run: git add .

      - name: Exit if there are no changes
        run: git diff --exit-code --cached

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "docs(protocol): auto-update protocol documentation"
          git push

      - name: Create pull request
        if: |
          github.event.pull_request.merged == true &&
          github.event.diff_status == 'modified'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "docs(protocol): auto-update protocol documentation"
          head: update-docs-${{ github.sha }}
          base: main
